(() => {
  'use strict';
  const $=id=>document.getElementById(id),session=document.querySelector('meta[name="mokda-session"]').content;
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const languages={KR:'한국어',ES:'Español',EN:'English'};
  let snapshot,currentId,creating=false,dirty=false,busy=false;
  function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('is-error',error);}
  function lock(value){busy=value;document.querySelectorAll('#saveStory,#newStory,.story-select,#mediaUpload').forEach(el=>{el.disabled=value;});}
  async function request(url,options={}){const response=await fetch(url,{...options,headers:{'X-Mokda-Session':session,...options.headers}});const data=await response.json();if(!response.ok)throw new Error(data.error||'요청하지 못했습니다.');return data;}
  function showLanguage(lang){document.querySelectorAll('[data-lang]').forEach(button=>{const active=button.dataset.lang===lang;button.setAttribute('aria-selected',String(active));button.tabIndex=active?0:-1;$('panel'+button.dataset.lang).hidden=!active;});}
  $('languageEditors').innerHTML=Object.entries(languages).map(([lang,label])=>`<section class="language-panel" id="panel${lang}" role="tabpanel" aria-labelledby="tab${lang}" hidden><label>${label} 제목<input data-field="title" maxlength="180"></label><label>요약<textarea data-field="summary" maxlength="400" rows="2"></textarea></label><label>사진 설명 <span>이미지 대체 텍스트</span><input data-field="imageAlt" maxlength="240"></label><label>사진 캡션 <span>선택</span><input data-field="imageCaption" maxlength="400"></label><label>본문<textarea data-field="body" rows="10" placeholder="## 소제목&#10;본문 내용을 적어주세요."></textarea></label></section>`).join('');
  document.querySelectorAll('[data-lang]').forEach((button,index,buttons)=>{
    button.addEventListener('click',()=>showLanguage(button.dataset.lang));
    button.addEventListener('keydown',event=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(event.key)){event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?2:(index+(event.key==='ArrowRight'?1:2))%3;showLanguage(buttons[next].dataset.lang);buttons[next].focus();}});
  });
  function mediaOptions(selectedImage,selectedVideo){$('image').innerHTML=snapshot.assets.images.map(name=>`<option value="${esc(name)}">${esc(name)}</option>`).join('');$('video').innerHTML='<option value="">영상 없음</option>'+snapshot.assets.videos.map(name=>`<option value="${esc(name)}">${esc(name)}</option>`).join('');$('image').value=selectedImage||snapshot.assets.images[0]||'';$('video').value=selectedVideo||'';updatePreview();}
  function updatePreview(){const name=$('image').value;$('coverPreview').src=name?'/media/'+name+'-640.webp':'';$('coverPreview').hidden=!name;}
  function renderList(){const category={news:'소식·미디어',events:'행사',collaborations:'콜라보'};$('storyList').innerHTML=[...snapshot.data.stories].sort((a,b)=>(b.publishedDate||snapshot.data.publishedDate).localeCompare(a.publishedDate||snapshot.data.publishedDate)).map(story=>`<button type="button" class="story-select${story.id===currentId?' is-active':''}" data-story="${story.id}"><strong>${esc(story.KR.title)}</strong><span>${esc(category[story.category])} / ${esc(story.publishedDate||snapshot.data.publishedDate)}${story.homeFeatured?' / 홈 '+story.homeOrder:''}</span></button>`).join('');document.querySelectorAll('[data-story]').forEach(button=>button.addEventListener('click',()=>select(button.dataset.story)));}
  function select(id){if(busy)return;if(dirty&&!confirm('저장하지 않은 변경이 있습니다. 다른 소식을 열까요?'))return;currentId=id;creating=!id;dirty=false;
    const story=snapshot.data.stories.find(s=>s.id===id);renderList();$('editorMode').textContent=creating?'새 소식 등록':'소식 수정';$('editorTitle').textContent=story?.KR.title||'새로운 MOKDA 이야기';$('homeBadge').textContent=story?.homeFeatured?'홈 노출 '+story.homeOrder:'';
    $('storyId').value=story?.id||'';$('storyId').disabled=!creating;$('category').value=story?.category||'news';$('location').value=story?.location||'';$('publishedDate').value=story?.publishedDate||new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'});$('eventDate').value=story?.eventDate||'';$('eventEndDate').value=story?.eventEndDate||'';$('homePosition').value=story?.homeFeatured?String(story.homeOrder):'0';$('homeCreators').checked=!!snapshot.data.settings?.homeCreators;$('gallery').value=(story?.gallery||[]).join(', ');mediaOptions(story?.image,story?.video);
    for(const lang of Object.keys(languages)){const panel=$('panel'+lang),copy=story?.[lang];for(const field of ['title','summary','imageAlt','imageCaption'])panel.querySelector(`[data-field="${field}"]`).value=copy?.[field]||'';panel.querySelector('[data-field="body"]').value=(copy?.sections||[]).map(([heading,body])=>'## '+heading+'\n'+body).join('\n\n');}
    $('relatedStories').innerHTML=snapshot.data.stories.filter(s=>s.id!==id).map(s=>`<label><input type="checkbox" value="${s.id}"${story?.related.includes(s.id)?' checked':''}>${esc(s.KR.title)}</label>`).join('');showLanguage('KR');status('');
  }
  function sections(text,lang){const parts=text.trim().split(/^##\s+/m);if(parts[0].trim()||parts.length<2)throw new Error(`${lang} 본문은 ‘## 소제목’으로 시작해주세요.`);return parts.slice(1).map(part=>{const lines=part.split('\n');return [lines.shift().trim(),lines.join('\n').trim()];});}
  function record(){const result={id:$('storyId').value.trim(),category:$('category').value,publishedDate:$('publishedDate').value,location:$('location').value.trim(),eventDate:$('eventDate').value,eventEndDate:$('eventEndDate').value,homePosition:Number($('homePosition').value),image:$('image').value,video:$('video').value,gallery:$('gallery').value.split(',').map(s=>s.trim()).filter(Boolean),related:[...$('relatedStories').querySelectorAll('input:checked')].map(el=>el.value)};
    for(const lang of Object.keys(languages)){const panel=$('panel'+lang);result[lang]={};for(const field of ['title','summary','imageAlt','imageCaption'])result[lang][field]=panel.querySelector(`[data-field="${field}"]`).value.trim();result[lang].sections=sections(panel.querySelector('[data-field="body"]').value,lang);}return result;}
  $('editorForm').addEventListener('input',()=>{dirty=true;});$('image').addEventListener('change',updatePreview);$('newStory').addEventListener('click',()=>select(null));
  $('editorForm').addEventListener('submit',async event=>{event.preventDefault();if(busy)return;try{const payload={record:record(),revision:snapshot.revision,create:creating,homeCreators:$('homeCreators').checked};lock(true);status('저장하고 3개 언어 미리보기를 갱신하고 있습니다…');const result=await request('/api/news',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});snapshot=result;dirty=false;lock(false);select(payload.record.id);status(result.built?'저장 완료. 미리보기를 새로고침하면 반영된 내용을 볼 수 있습니다.':result.warning,!result.built);}catch(error){status(error.message,true);const match=/^(KR|ES|EN)/.exec(error.message);if(match)showLanguage(match[1]);}finally{lock(false);}});
  $('mediaUpload').addEventListener('change',async()=>{const file=$('mediaUpload').files[0];if(!file)return;if(file.size>100*1024*1024){status('최대 100MB 파일을 선택해주세요.',true);return;}try{lock(true);status('미디어를 추가하고 웹 표시용으로 변환하고 있습니다…');const result=await request('/api/media',{method:'POST',headers:{'Content-Type':file.type||'application/octet-stream'},body:file});const image=$('image').value,video=$('video').value;snapshot.assets=result.assets;mediaOptions(result.kind==='image'?result.name:image,result.kind==='video'?result.name:video);dirty=true;status('미디어 추가 완료. 소식을 저장하면 반영됩니다.');}catch(error){status(error.message,true);}finally{$('mediaUpload').value='';lock(false);}});
  window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
  request('/api/news').then(result=>{snapshot=result;select(result.data.stories[0]?.id||null);}).catch(error=>status(error.message,true));
})();
